# Generated by Django 4.2.4 on 2023-08-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichMenu', '0002_remove_sandwich_ingredients_sandwich_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sandwich',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='SandwichMenu.sandwich'),
        ),
    ]
